pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label=ready-to-merge
      - check-success=build
    actions:
      merge:
        method: merge
        commit_message: title+body
